//
//  Races.swift
//  RpgCards
//
//  Created by Michal on 22.06.2018.
//  Copyright © 2018 Prograils.com. All rights reserved.
//

import Foundation

public let racesArray: [String: String] = [
//Currently avaialbe only got GamesIcons font
    "game-icon-spartan": "\u{e02F}",
    "game-icon-female": "\u{e066}",
    "game-icon-king": "\u{e0A9}",
    "game-icon-dwarf-king": "\u{e0CC}",
    "game-icon-frog-prince": "\u{e0E1}",
    "game-icon-spy": "\u{e0FC}",
    "game-icon-archer": "\u{e129}",
    "game-icon-william-tell": "\u{e195}",
    "game-icon-fire-silhouette": "\u{e25D}",
    "game-icon-ifrit": "\u{e26E}",
    "game-icon-pyromaniac": "\u{e276}",
    "game-icon-salamander": "\u{e277}",
    "game-icon-spark-spirit": "\u{e279}",
    "game-icon-spider-face": "\u{e281}",
    "game-icon-mounted-knight": "\u{e28D}",
    "game-icon-bear-face": "\u{e290}",
    "game-icon-eagle-head": "\u{e29D}",
    "game-icon-elephant-head": "\u{e29E}",
    "game-icon-gorilla": "\u{e2A6}",
    "game-icon-horse-head": "\u{e2A8}",
    "game-icon-lynx-head": "\u{e2AC}",
    "game-icon-minotaur": "\u{e2F5}",
    "game-icon-parrot-head": "\u{e2FD}",
    "game-icon-snake-totem": "\u{e30D}",
    "game-icon-werewolf": "\u{e321}",
    "game-icon-wolf-head": "\u{e323}",
    "game-icon-worm-mouth": "\u{e326}",
    "game-icon-card-joker": "\u{e379}",
    "game-icon-acrobatic": "\u{e390}",
    "game-icon-running-ninja": "\u{e392}",
    "game-icon-public-speaker": "\u{e3A3}",
    "game-icon-teacher": "\u{e3A9}",
    "game-icon-meditation": "\u{e3B6}",
    "game-icon-prayer": "\u{e3BB}",
    "game-icon-medusa-head": "\u{e3F6}",
    "game-icon-witch-face": "\u{e3F9}",
    "game-icon-dragon-head": "\u{e3FA}",
    "game-icon-troll": "\u{e3FC}",
    "game-icon-centaur": "\u{e406}",
    "game-icon-fairy": "\u{e40A}",
    "game-icon-female-vampire": "\u{e40B}",
    "game-icon-giant": "\u{e410}",
    "game-icon-goblin-head": "\u{e411}",
    "game-icon-golem-head": "\u{e412}",
    "game-icon-mermaid": "\u{e41C}",
    "game-icon-mummy-head": "\u{e41F}",
    "game-icon-ogre": "\u{e420}",
    "game-icon-troglodyte": "\u{e42B}",
    "game-icon-daemon-skull": "\u{e433}",
    "game-icon-diablo-skull": "\u{e434}",
    "game-icon-ent-mouth": "\u{e43A}",
    "game-icon-frankenstein-creature": "\u{e444}",
    "game-icon-ghost": "\u{e445}",
    "game-icon-imp": "\u{e44F}",
    "game-icon-lizardman": "\u{e451}",
    "game-icon-wave-surfer": "\u{e486}",
    "game-icon-heavy-fighter": "\u{e494}",
    "game-icon-light-fighter": "\u{e495}",
    "game-icon-ufo": "\u{e4DF}",
    "game-icon-walking-scout": "\u{e4E2}",
    "game-icon-saber-toothed-cat-head": "\u{e4FA}",
    "game-icon-elf-ear": "\u{e509}",
    "game-icon-human-ear": "\u{e50E}",
    "game-icon-new-born": "\u{e586}"
]
